# Generated by Django 2.1.3 on 2018-12-04 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eggs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=200)),
                ('quantity', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('type', models.CharField(max_length=6)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
